name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: apt-get update
      run: sudo apt-get update
    - name: apt-get install
      run: |
        sudo apt-get install -y pkg-config build-essential ca-certificates
    - name: Set up cargo cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
          .custom_models/
          .fastembed_cache/
        key: cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: cargo-
    - name: Install target
      run: rustup target add x86_64-unknown-linux-gnu
    - name: Environment
      run: |
        gcc --version
        g++ --version
        rustc --version
        cargo --version
    - name: Check & Fmt & Clippy
      run: |
        cargo check
        cargo fmt -- --check
        cargo clippy
    - name: Build
      run: |
        cargo build
